codegen: Fix function pointer mypy errors
typeshed was missing the no-arguments constructor for `_ctypes.CFuncPtr`
until very recently.
https://github.com/python/typeshed/pull/10154

generated\nidaqmx\_library_interpreter.py:4414: error: All overload variants of "_FuncPointer" require at least one argument  [call-overload]
generated\nidaqmx\_library_interpreter.py:4414: note: Possible overload variants:
generated\nidaqmx\_library_interpreter.py:4414: note:     def _FuncPointer(self, address: int) -> _FuncPointer
generated\nidaqmx\_library_interpreter.py:4414: note:     def _FuncPointer(self, callable: Callable[..., Any]) -> _FuncPointer
generated\nidaqmx\_library_interpreter.py:4414: note:     def _FuncPointer(self, func_spec: Tuple[Union[str, int], CDLL], paramflags: Tuple[Union[Tuple[int], Tuple[int, str], Tuple[int, str, Any]], ...] = ...) -> _FuncPointer
generated\nidaqmx\_library_interpreter.py:4414: note:     def _FuncPointer(self, vtlb_index: int, name: str, paramflags: Tuple[Union[Tuple[int], Tuple[int, str], Tuple[int, str, Any]], ...] = ..., iid: _Pointer[c_int] = ...) -> _FuncPointer

Signed-off-by: Brad Keryan <brad.keryan@ni.com>