codegen: Fix argtypes mypy errors
argtypes should be a list of types. Change ctypes_bytes_str.from_param
from an instance method to a class method so that we can add the type
to argtypes like normal, not the instance.

generated\nidaqmx\_library_interpreter.py:2258: error: Argument 1 to "append" of "list" has incompatible type "Type[_Pointer[c_double]]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2261: error: Argument 1 to "append" of "list" has incompatible type "Type[c_int32]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2264: error: Argument 1 to "append" of "list" has incompatible type "Type[c_void_p]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2636: error: Argument 1 to "append" of "list" has incompatible type "Type[_Pointer[c_int32]]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2639: error: Argument 1 to "append" of "list" has incompatible type "Type[c_void_p]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2662: error: Argument 1 to "append" of "list" has incompatible type "Type[_Pointer[c_int32]]"; expected "CtypesByteString"  [arg-type]
generated\nidaqmx\_library_interpreter.py:2665: error: Argument 1 to "append" of "list" has incompatible type "Type[c_void_p]"; expected "CtypesByteString"  [arg-type]

Signed-off-by: Brad Keryan <brad.keryan@ni.com>