handwritten: Fix mypy errors in task.py
`read()` and `write()` had a lot of mypy errors:
- `array_shape` is either a tuple of ints or a single int. Change to be a variable-sized tuple of ints.
- `data` is a list of named tuples for counter pulse and power, and an ndarray for everything else. Extract `_read_ctr_pulse` and `_read_power` helper methods to clean this up.
- `data` and other variables are reused to build lists with for-loops. Convert these to use list comprehensions.
- Convert the power meas_type check to use a generator expression.
- `numpy.asarray` is for converting values that may already be an ndarray. Use `numpy.array` when the input is definitely not an ndarray.
- Add some else cases to catch unexpected meas/output types.

generated\nidaqmx\task.py:614: error: Incompatible types in assignment (expression has type "int", variable has type "tuple[int, Any]")  [assignment]
generated\nidaqmx\task.py:650: error: Argument 1 to "append" of "list" has incompatible type "list[PowerMeasurement]"; expected "PowerMeasurement"  [arg-type]
generated\nidaqmx\task.py:663: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[PowerMeasurement]")  [assignment]
generated\nidaqmx\task.py:671: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[Any]]", variable has type "list[PowerMeasurement]")  [assignment]
generated\nidaqmx\task.py:676: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[unsignedinteger[_32Bit]]]", variable has type "list[PowerMeasurement]")  [assignment]
generated\nidaqmx\task.py:694: error: Argument 1 to "append" of "list" has incompatible type "CtrFreq"; expected "PowerMeasurement"  [arg-type]
generated\nidaqmx\task.py:705: error: Argument 1 to "append" of "list" has incompatible type "CtrTime"; expected "PowerMeasurement"  [arg-type]
generated\nidaqmx\task.py:716: error: Argument 1 to "append" of "list" has incompatible type "CtrTick"; expected "PowerMeasurement"  [arg-type]
generated\nidaqmx\task.py:719: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[unsignedinteger[_32Bit]]]", variable has type "list[PowerMeasurement]")  [assignment]
generated\nidaqmx\task.py:726: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[PowerMeasurement]")  [assignment]
generated\nidaqmx\task.py:753: error: "list[PowerMeasurement]" has no attribute "tolist"  [attr-defined]
generated\nidaqmx\task.py:757: error: No overload variant of "__getitem__" of "list" matches argument type "tuple[slice, slice]"  [call-overload]
generated\nidaqmx\task.py:757: note: Possible overload variants:
generated\nidaqmx\task.py:757: note:     def __getitem__(self, SupportsIndex, /) -> PowerMeasurement
generated\nidaqmx\task.py:757: note:     def __getitem__(self, slice, /) -> list[PowerMeasurement]
generated\nidaqmx\task.py:759: error: "list[PowerMeasurement]" has no attribute "tolist"  [attr-defined]
generated\nidaqmx\task.py:761: error: "list[PowerMeasurement]" has no attribute "tolist"  [attr-defined]
generated\nidaqmx\task.py:1261: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[Any]")  [assignment]
generated\nidaqmx\task.py:1262: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[Any]")  [assignment]
generated\nidaqmx\task.py:1275: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[Any]")  [assignment]
generated\nidaqmx\task.py:1276: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[floating[_64Bit]]]", variable has type "list[Any]")  [assignment]
generated\nidaqmx\task.py:1289: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[unsignedinteger[_32Bit]]]", variable has type "list[Any]")  [assignment]
generated\nidaqmx\task.py:1290: error: Incompatible types in assignment (expression has type "ndarray[Any, dtype[unsignedinteger[_32Bit]]]", variable has type "list[Any]")  [assignment]