codegen, handwritten: Use tuple for empty __slots__
Work around https://github.com/python/mypy/issues/10870 - Mypy complains
when [] is used for __slots__ definition

generated\nidaqmx\_base_interpreter.py:8: error: Need type annotation for "__slots__" (hint: "__slots__: List[<type>] = ...")  [var-annotated]

Signed-off-by: Brad Keryan <brad.keryan@ni.com>