examples: Enable mypy for the example programs (#879)
* examples: Enable mypy

* examples: Fix error: Incompatible types in assignment (expression has type "list[bool]", variable has type "bool")  [assignment]

* examples: Ignore missing imports for nptdms

* github: Update check.yml to install examples dependency group

* docs: Add --with examples to CONTRIBUTING.md

* examples: Fix Linux mypy errors